### ISSUE TITLE
[Feature request] Upgrade `source_gen` to version 0.9.0

### ISSUE THREAD

**Issue by cedx** [kevmoo/build_cli#16]
* [x] Dart SDK : `2.0.0-dev.69.2 (Mon Jul 23 17:10:56 2018 +0200) on "windows_x64"`
* [x] build_cli : `0.2.4+1`

I'm using packages `json_annotation` v1.0.0 and `json_serializable` v1.0.0 to add JSON support to some model classes to a project providing an executable that uses `build_cli`.

These packages rely on `source_gen` v0.9.0 but `build_cli` rely on v0.8.2. So I can't install the project dependencies :

```shell
$ pub get
Resolving dependencies...
Because build_cli >=0.2.4 depends on source_gen ^0.8.2 and json_serializable >=1.0.0 depends on source_gen ^0.9.0, build_cli >=0.2.4 is incompatible with json_serializable >=1.0.0.
So, because my_app depends on both json_serializable ^1.0.0 and build_cli ^0.2.4, version solving failed.
```

**Comment by kevmoo** [comment]
I'll get on that now! (Glad to know someone else is using build_cli.) :-)

**Comment by cedx** [comment]
Wonderful! And thanks a lot.

I came across this package really by chance: I saw that `dhttpd` had been updated to version 3.0.0, I watched the changes, and voilà! Having typed CLI options is nice.

**Comment by kevmoo** [comment]
😁 – so glad! Tell your friends!

**Comment by kevmoo** [comment]
v0.2.5 is published!

**Comment by cedx** [comment]
A big thank-you. I'm already up to date :)
