### ISSUE TITLE
Support commands on a parsed class.

### ISSUE THREAD

**Issue by Kleak** [kevmoo/build_cli#29]
is there a way with build_cli to use addCommand ? if yes how ?

thanks

**Comment by kevmoo** [comment]
The generator creates a final field w/ each parser. Look for `final _$parserForMyClass`.

You can always add commands to this. You can even add commands w/ parsers that are also generated.

I've thought about wiring this up w/ a bit of magic, but it'd be work. I'll leave this issue open to track it!

**Comment by magillus** [comment]
@Kleak do you mean to be something like: https://ajalt.github.io/clikt/ 
Have a command and options and allow nested commands/subcommands?

**Comment by Kleak** [comment]
@magillus I was more thinking about support for https://pub.dev/packages/args#defining-commands inside build_cli :

**Comment by magillus** [comment]
I got small proposal to add Commands with subcommands with `build_cli`
### Definition for CliCommand annotation

```dart

class CliCommand {
  final String name;
  const CliCommand(this.name);
}
```

### Commands definitions
```dart
import 'package:build_cli_annotations/build_cli_annotations.dart';

// part 'example_cmd.g.dart'; uncomment after full builder generation

@CliCommand('test')
class TestCommand {
  @CliOption(abbr: 'p', help: 'Required. Port for connection.')
  final int port;
  TestCommand(this.port, {this.helpSubCommand});

  HelpCommand helpSubCommand;
}

@CliCommand('help')
class HelpCommand {
  String phrase;
  HelpCommand(this.phrase);
}
```

#### Generated extensions with static methods 

```dart
/// GENERATED code would look like this.

TestCommand parseTestCommand(List<String> args) {
  final parser = ArgParser();

  parser.addCommand('test').addOption(
        'port',
        abbr: 'p',
        help: 'Required. Port for connection',
      );

  final parsedArgs = parser.parse(args);

  return TestCommand(int.parse(parsedArgs.command['port'].toString()))
    ..helpSubCommand = parseHelpCommand(parsedArgs.command.rest);
}

/// GENERATED code for Help Command
HelpCommand parseHelpCommand(List<String> args) {
  print('parsing: $args');
  final parser = ArgParser().addCommand('help');
  final parsedArgs = parser.parse(args);
  print('phrase= ${parsedArgs.command.rest.first}');
  return HelpCommand(parsedArgs.command.rest.first);
}
```

Usage.
```dart
/// USAGE
void main(List<String> args) {
  final cmd = parseTestCommand(args);

  print('cmd first : test port = ${cmd.port}');
  print('cmd second: help = ${cmd?.helpSubCommand?.phrase}');
}

```

If that gets 👌 from you folks, I am happy to add this generator and make a PR.

I would also think of support and autodetection for order of commands for the command lines:

`myexecutable cmdA -optionA 3334 cmdB -optionB 111` 
`myexecutable cmdB - optionB 111 cmdA -optionA 3334`

both would give same output?

However that breaks the support **SubCommand** from Args.

Maybe we can do a function `parseTestCommand` would extract only that command details from all command line `args`, no matter where positioned, so if above case:

`parseHelpCommand(args)` would return `HelpCommand` 
`parseTestCommand(args)` would return `TestCommand` and also with subcommand if it is defined as field?

Let me hear your thoughts.

**Comment by magillus** [comment]
@Kleak @kevmoo  let me know if that suits your idea - so I can proceed to start on PR without spending time on something that would not "merge"

**Comment by kevmoo** [comment]
But how do you support adding multiple commands to a single parser?

**Comment by magillus** [comment]
I found out that the `parsedArgs.command.rest` is everything left not defined in `CliCommand`, so it is still can be parsed as normal arguments.
Each command parse static method that would take any CLI arguments and extract only that command's options or flags, returning the class instance with `CliCommand` annotation.

If  the `CliCommand` class has the subcommand it would also try to populate that command's details, we could probably add on "optional" flag into annotation for the subcommand.

Also I would add global parse method that parses all CLI arguments and return `List<CliCommand>`

**Comment by vargavince91** [comment]
Based on https://pub.dev/packages/args#dispatching-commands, would the package need a command runner annotation, too?

How would the annotations look like for the commands-subcommands example in the `args` package?

```
git            (command runner)
  * commit     (command)
  * stash      (command)
    - save     (subcommand)
    - list     (subcommand)
```

Note: save and list are subcommands in the above example, but they are actually instances of the `Command` class.

Could this all be represented in the annotations?

**Comment by fzyzcjy** [comment]
+1 a few years have passed. Is there any updates?

**Comment by kevmoo** [comment]
@fzyzcjy – I'm slammed with many other things. I haven't had time to dig in here (yet)

**Comment by fzyzcjy** [comment]
@kevmoo Take your time and thanks for the reply

**Comment by fzyzcjy** [comment]
@kevmoo If I make a PR and implement this, will it be merged?

**Comment by kevmoo** [comment]
Uh...maybe? If it's well done, likely!

**Comment by kevmoo** [comment]
I'd spend a little time and write up some sample code and maybe a couple paragraphs about your approach so we can talk about it first

**Comment by fzyzcjy** [comment]
@kevmoo Sure 😄 I will come up with a sample code first

**Comment by fzyzcjy** [comment]
@kevmoo Example added: https://github.com/kevmoo/build_cli/pull/99/files

**Comment by magillus** [comment]
I totally forgot about it as life moved on.

**Comment by fzyzcjy** [comment]
No worries - I have implemented it already
